# Generated by Django 5.0.6 on 2024-08-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_name', models.CharField(max_length=255)),
                ('price_band', models.CharField(max_length=50)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('issue_size', models.CharField(max_length=50)),
                ('issue_type', models.CharField(max_length=50)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('ipo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listing_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rhp_url', models.URLField(blank=True, max_length=500, null=True)),
                ('drhp_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
